<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--<PackageIcon>icon.png</PackageIcon>-->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>0.9</MinVerMinimumMajorMinor>
    <MinVerAutoIncrement>patch</MinVerAutoIncrement>
    <MinVerDefaultPreReleaseIdentifiers>alpha.0</MinVerDefaultPreReleaseIdentifiers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TUnitImplicitUsings>true</TUnitImplicitUsings>
    <TUnitAssertionsImplicitUsings>true</TUnitAssertionsImplicitUsings>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)testconfig.json">
      <Link>$(AssemblyName).testconfig.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
